### ISSUE TITLE
Breaks SLES 12 package management

### ISSUE THREAD

**Issue by jkohen** [certifi/python-certifi#102]
# Repro
1. Launch a SLES 12 SP4 VM, e.g. at https://console.cloud.google.com/compute/instancesDeploySolution?solution=suse-cloud:sles-12
2. wget https://bootstrap.pypa.io/get-pip.py
3. sudo -E python3 get-pip.py
4. sudo -E python3 -m pip install 'certifi>=2017.4.17'
5. sudo zypper refresh

I've tried multiple certif versions between 2017.4.17 and 2019.3.9 (the latest as at now), and all fail with the following error:

  File "/usr/lib64/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/zypp/plugins/services/SMT-http_smt-gce_susecloud_net", line 111, in <module>
    headers=headers
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

# Workaround
Install the native certifi package with `sudo zypper install python3-certifi`. This prevents pip from installing certifi, which is useful when it gets pulled in as a dependency from another package, such as the Google Cloud libraries.

**Comment by Lukasa** [comment]
In general you cannot assume you can mix third-party Python packages with system ones if your system uses them. In this case, your system seems to use Requests as part of zypper, which will pick up a copy of certifi if one is available.

Please use a virtualenv.
