### ISSUE TITLE
No attribute 'where'

### ISSUE THREAD

**Issue by Gokujo** [certifi/python-certifi#107]
hey,
I have an issue with this plugin required by requests:
```Python3
certifi.where()
Traceback (most recent call last):
  File "D:\Python\Anaconda3\envs\conda3.6\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-52306e7169cb>", line 1, in <module>
    certifi.where()
AttributeError: module 'certifi' has no attribute 'where'
```

I tried to reinstall this plugin but it didn't helped even on different environment

**Comment by alex** [comment]
This looks like a severely broken certifi installation, sorry we didn't get back to this issue quickly, but I don't believe this is a bug in us.
