### ISSUE TITLE
ssl.SSLCertVerificationError after running the executable created using PyInstaller

### ISSUE THREAD

**Issue by krishtej23** [certifi/python-certifi#181]
I am using `0.1.14` version of polarion. Without the pyinstaller, when I run the below code in PyCharm, script can make the connection. 
```
from polarion import polarion
from getpass import getpass

server = 'https://server/'
username = input("Enter UserId: ")
pwd = getpass()

ps = polarion.Polarion(server, username, pwd)

projID = input("Please enter the project ID: ")
projectObj = ps.getProject(projID)

print("Parent ID:")
```
but the below error pops up when running the executable.
```
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "polarion-playground.py", line 8, in <module>
  File "polarion\polarion.py", line 38, in __init__
  File "polarion\polarion.py", line 57, in _getServices
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='server', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
[19768] Failed to execute script 'polarion-playground' due to unhandled exception!
Exception ignored in: <function Polarion.__del__ at 0x000002650E051B80>
Traceback (most recent call last):
  File "polarion\polarion.py", line 43, in __del__
KeyError: 'Session'
```
The same kind of issue popped up twice [https://github.com/pyinstaller/pyinstaller/issues/6403#issuecomment-983000186](url) and here is the solution proposed there. To add the below lines at the start of my code and now the issue is gone.
```
import sys
if getattr(sys, 'frozen', False) and sys.platform == 'win32':
    import certifi
    import certifi_win32.wincerts
    
    certifi_win32.wincerts.CERTIFI_PEM = certifi.where()
    
    certifi.where =  certifi_win32.wincerts.where
    
    from certifi_win32.wincerts import generate_pem, verify_combined_pem
    if not verify_combined_pem():
        generate_pem()
```
Is there anyway to have a solution without the need for the above code?

**Comment by sigmavirus24** [comment]
We don't own polarion or certifi_win32. This is a problem that pyinstaller and certifi_win32 need to sort out.
