### ISSUE TITLE
Upgrading certifi lib to 2022.6.15 resulted in SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by lorenzoPatras** [certifi/python-certifi#197]
I am using aiohttp (3.8.1) to make requests to `https://autocomplete.search.hereapi.com/v1/autocomplete`. Yesterday I updated the libraries for my project including `certifi` from `2022.5.18.1` to `2022.6.15` and requests to here result in ssl.SSLCertVerificationError. I ran the `Install Certificates.command` and `Update Shell Profile.command` commands and the requests are still failing.

Sample code:
```
async def plm():
    async with aiohttp.ClientSession() as session:
        parameters = {
            "q": "ams",
            "apiKey": ***
        }

        get_url = "https://autocomplete.search.hereapi.com/v1/autocomplete"
        async with session.get(get_url, params=parameters) as response:
            print(response)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(plm())
``` 

Exception stack:
```
Traceback (most recent call last):
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lorenzo.patras/rbl/py_playground/main.py", line 58, in <module>
    loop.run_until_complete(plm())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lorenzo.patras/rbl/py_playground/main.py", line 53, in plm
    async with session.get(get_url, params=parameters) as response:
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/lorenzo.patras/rbl/py_venv_generic/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host autocomplete.search.hereapi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')]

```

**Comment by pachois** [comment]
I'm receiving the same error message, except I didn't update the certifi version. The code was working fine in an AWS Lambda and all of a sudden this error popped up. Haven't been able to figure out a solution.

**Comment by teiresias** [comment]
I got the error using kivy with openssl1.1m. Downgrading openssl to 1.1k version fixed it. So maybe this error is related to openssl version >1.1k

**Comment by pachois** [comment]
I resolved my issue, it was not related to one of the packages, it was the certificate itself. I downloaded the certificates from the site I was working with and bundled them with the ca certificate from certifi. After that things started working again, all packages are up to date.

**Comment by Kshitij4kk** [comment]
@pachois , can you kindly tell me how did you update your certifi cacert.pem file ? 
I am observing similar SSL: CERTIFICATE_VERIFY_FAILED issue . I have documented here: https://stackoverflow.com/questions/73744639/getting-ssl-certificate-verify-failed-error-in-python-while-trying-requests-p

I hope that clubbing the client ca certificate with certifi cacert.pem should resolve my error too but I am unware of the process on how to achieve that.

**Comment by pachois** [comment]
- download\export the certificate of the site you're working with
- open it with your preferred text editor (Notepad++, Atom, etc.)
- copy the certificate 
------BEGIN CERTIFICATE-----
:certificate:
-----END CERTIFICATE-----
- paste it at the end of cacert.pem

**Comment by Kshitij4kk** [comment]
> * download\export the certificate of the site you're working with
> * open it with your preferred text editor (Notepad++, Atom, etc.)
> * copy the certificate
>   ------BEGIN CERTIFICATE-----
>   :certificate:
>   -----END CERTIFICATE-----
> * paste it at the end of cacert.pem

Thanks @pachois for the help.
