### ISSUE TITLE
Support for python 2.5

### ISSUE THREAD

**Issue by pyhedgehog** [certifi/python-certifi#38]
Setup (and pypi metadata) insists that certifi package supports python 2.5:
https://github.com/certifi/python-certifi/blob/38502797954603558ebf5f2c93f3645279e18158/setup.py#L45

But in same file it uses construction that is incompatible:
https://github.com/certifi/python-certifi/blob/38502797954603558ebf5f2c93f3645279e18158/setup.py#L10

Result is:

``` console
C:\>py -2.5 -m pip install --insecure requests==0.10.0
Downloading/unpacking requests==0.10.0
  Downloading requests-0.10.0.tar.gz (62kB): 62kB downloaded
  Running setup.py egg_info for package requests
Downloading/unpacking certifi>=0.0.4 (from requests==0.10.0)
  Downloading certifi-2016.2.28.tar.gz (364kB): 364kB downloaded
  Running setup.py egg_info for package certifi
    c:\users\XXXX\appdata\local\temp\pip-build-XXXX\certifi\setup.py:10: Warning: 'with' will become a reserved keyword in Python 2.6
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\XXXX\appdata\local\temp\pip-build-XXXX\certifi\setup.py", line 10
        with open('certifi/__init__.py', 'r') as f:
                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    c:\users\XXXX\appdata\local\temp\pip-build-XXXX\certifi\setup.py:10: Warning: 'with' will become a reserved keyword in Python 2.6

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\XXXX\appdata\local\temp\pip-build-XXXX\certifi\setup.py", line 10

    with open('certifi/__init__.py', 'r') as f:

            ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in c:\users\XXXX\appdata\local\temp\pip-build-XXXX\certifi
Storing complete log in c:\users\XXXX\appdata\local\temp\tmpdt40ir
```

**Comment by sigmavirus24** [comment]
I'm uncertain why we claim to support it, but I think we should remove that misleading information. Do you agree @Lukasa?

**Comment by sigmavirus24** [comment]
That said, if there's some special reason for supporting 2.5 we can just do

```py
from __future__ import print_statement
```

But I don't have 2.5 to determine if there's anything else that would break for us (although there shouldn't be).

**Comment by Lukasa** [comment]
@sigmavirus24 I'd be open to *also* removing the trove classifier for Python 2.5.
