### ISSUE TITLE
  pkg_resources.VersionConflict: (certifi 2018.4.16 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('certifi==2016.9.26'))

### ISSUE THREAD

**Issue by gerroon** [certifi/python-certifi#87]
Hi

I am sorry to post this here but I am totally unable to solve this issue, so I am hitting a corner case here or I need help from the devs. 

I am using Debian testing (buster/sid). I cant install anything through pip except certifi itself. I am stuck and I need to install bunch of stuff :(

I cant uninstall the Debians's version because it is going to break my system if I do.

```
pip install certifi

Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (2018.4.16)
python-debianbts 2.7.2 requires pysimplesoap, which is not installed.

```

It seems to work with importing
```
 python

Python 2.7.15 (default, May  1 2018, 05:55:50) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
>>> certifi.where()
'/etc/ssl/certs/ca-certificates.crt'

```

This is a sample error

```
Collecting Mopidy-Radio-Rough
  Using cached https://files.pythonhosted.org/packages/6c/f0/7d1d89a45d8f56874e9d231249e6e9100e75e63331506dbb43e910142a21/Mopidy_Radio_Rough-3.14.15-py2.py3-none-any.whl
Requirement already satisfied: Mopidy>=1.0 in /usr/lib/python2.7/dist-packages (from Mopidy-Radio-Rough) (2.1.0)
Requirement already satisfied: Pykka>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy-Radio-Rough) (1.2.1)
Requirement already satisfied: feedparser in /usr/lib/python2.7/dist-packages (from Mopidy-Radio-Rough) (5.2.1)
Collecting jsonpickle (from Mopidy-Radio-Rough)
  Using cached https://files.pythonhosted.org/packages/32/d5/2f47f03d3f64c31b0d7070b488274631d7567c36e81a9f744e6638bb0f0d/jsonpickle-0.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module backports was already imported from None, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
      from pkg_resources import Distribution, PathMetadata, ensure_directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/root/pip-install-_MoZNJ/jsonpickle/setup.py", line 54, in <module>
        setup_mod.setup(**SETUP_ARGS)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 592, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (certifi 2018.4.16 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('certifi==2016.9.26'))
```

**Comment by Lukasa** [comment]
I think that you’re installing into the global package store. This isn’t going to go well: you should `apt-get install python-virtualenv` and then create a `virtualenv` to use for installation.

**Comment by gerroon** [comment]
@Lukasa 

Can you please tell me the steps to do it? I am not a Py dev unfortunately :(
