### ISSUE TITLE
Upgrade to certify 2018.04.16

### ISSUE THREAD

**Issue by dilyanpalauzov** [certifi/python-certifi#88]
After upgrading to certify 2018.04.16 with `pip2 install -U certify`, `pip2 list -o` prints
```
Traceback (most recent call last):
  File "/usr/local/bin/pip2", line 7, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 86, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```
Any idea why the previous 2018.01.18 worked, but 2018.04.16 does not?

**Comment by alex** [comment]
It is very unlikely that upgrading certifi caused this.

I suspect you upgraded pyOpenSSL or pyca/cryptography to a version not compatible with the other.

**Comment by dilyanpalauzov** [comment]
I had this problem actually months ago both with python3.6 and python2.7 and then deleted some files to get it working, but certifi was not upgraded, now I gave it another try.

So I tried to delete some files having certify 2018.1.16 installed, then do `pip install -U certifi` and complare the details of what happens.

Fortunately the problem disappeared, unfortunately the problem is not reproducible.  pip3 install -U certifi worked suggenly fine this time, in April it had problems.  After deleting some files in python2.7, I cannot tell anymore which, the upgrade also works.

For the record, while my system was broken, I had both /usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py and  /usr/local/lib/python2.7/dist-packages/pyOpenSSL-18.0.0-py2.7.egg/OpenSSL/SSL.py, and they were distinct.  Now I have only the former one.

Any idea why the files were distinct?

**Comment by dilyanpalauzov** [comment]
This is what `pip install -U certify` does:
```
Requirement already up-to-date: certify in /usr/local/lib/python3.6/site-packages (1.0rc6)
Collecting click<5.0,>=4.0 (from certify)
  Using cached https://files.pythonhosted.org/packages/6e/97/f25f4277d90efa3d34ced57137023ecb96e0c9aacf79b4f93efe6d94a2f8/click-4.1-py2.py3-n
one-any.whl
Collecting pyopenssl<0.16,>=0.15 (from certify)
  Using cached https://files.pythonhosted.org/packages/37/2f/840f2656e4bcf257cb814825bb751a9197ca6f39f1fa036ab111920ac7ef/pyOpenSSL-0.15.1-py
2.py3-none-any.whl
Collecting requests<2.8,>=2.7 (from certify)
  Using cached https://files.pythonhosted.org/packages/26/ff/c71b3943bebdd9f7ceb9e137296370587eb0b33fe2eb3732ae168bc45204/requests-2.7.0-py2.
py3-none-any.whl
Requirement already satisfied, skipping upgrade: cryptography>=0.7 in /usr/local/lib/python3.6/site-packages (from pyopenssl<0.16,>=0.15->cer
tify) (2.3)
Requirement already satisfied, skipping upgrade: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from pyopenssl<0.16,>=0.15->certify) (
1.11.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /usr/local/lib/python3.6/site-packages (from cryptography>=0.7->pyopen
ssl<0.16,>=0.15->certify) (1.11.5)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography>=0.7->pyopen
ssl<0.16,>=0.15->certify) (0.24.0)
Requirement already satisfied, skipping upgrade: idna>=2.1 in /usr/local/lib/python3.6/site-packages (from cryptography>=0.7->pyopenssl<0.16,
>=0.15->certify) (2.7)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=
0.7->pyopenssl<0.16,>=0.15->certify) (2.18)
Installing collected packages: click, pyopenssl, requests
  Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
  Found existing installation: pyOpenSSL 18.0.0
    Uninstalling pyOpenSSL-18.0.0:
      Successfully uninstalled pyOpenSSL-18.0.0
  Found existing installation: requests 2.19.1
    Uninstalling requests-2.19.1:
      Successfully uninstalled requests-2.19.1
Successfully installed click-4.1 pyopenssl-0.15.1 requests-2.7.0
```
Why do have click, pyopenssl and requests lower versions after the upgrade?

**Comment by Lukasa** [comment]
Seems like a question for the pip folks. Certifi has no dependencies.
