### ISSUE TITLE
bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [certifi/python-certifi#90]
After 
```
pip3 download certifi==2018.4.16 --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)
```
root@host:/build/certifi-2018.4.16# python3 setup.py bdist_wheel upload -r artifactory
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '2018.04.16' to '2018.4.16'
  normalized_version,
running bdist_wheel
running build
running build_py
running egg_info
writing certifi.egg-info/PKG-INFO
writing dependency_links to certifi.egg-info/dependency_links.txt
writing top-level names to certifi.egg-info/top_level.txt
reading manifest file 'certifi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'certifi.egg-info/SOURCES.txt'
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/certifi
copying build/lib/certifi/core.py -> build/bdist.linux-ppc64le/wheel/certifi
copying build/lib/certifi/__main__.py -> build/bdist.linux-ppc64le/wheel/certifi
copying build/lib/certifi/cacert.pem -> build/bdist.linux-ppc64le/wheel/certifi
copying build/lib/certifi/__init__.py -> build/bdist.linux-ppc64le/wheel/certifi
running install_egg_info
Copying certifi.egg-info to build/bdist.linux-ppc64le/wheel/certifi-2018.4.16-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/certifi-2018.4.16.dist-info/WHEEL
creating '/build/certifi-2018.4.16/dist/certifi-2018.4.16-py2.py3-none-any.whl' and adding '.' to it
adding 'certifi/__init__.py'
adding 'certifi/__main__.py'
adding 'certifi/cacert.pem'
adding 'certifi/core.py'
adding 'certifi-2018.4.16.dist-info/LICENSE.txt'
adding 'certifi-2018.4.16.dist-info/top_level.txt'
adding 'certifi-2018.4.16.dist-info/WHEEL'
adding 'certifi-2018.4.16.dist-info/METADATA'
adding 'certifi-2018.4.16.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    'Programming Language :: Python :: 3.6',
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```
Debugging shows: key="platform", value=b'UNKNOWN'

**Comment by Lukasa** [comment]
That doesn’t look like it’s coming from this package. @dstufft any ideas?

**Comment by sigmavirus24** [comment]
A few things:

1. You should use twine to upload artifacts to repositories.

2. The latest versions of wheel have known issues trying to write to Artifactory because the software doesn't support the latest wheel metadata format.

3. This problem seems firmly in the [setuptools/distutils code](https://github.com/python/cpython/blob/112784984784199d54176132edc38ce8c9b007c1/Lib/distutils/command/upload.py#L162) and not in this project, as indicated by the traceback.

4. Your debugging doesn't make a whole lot of sense. The object that `body` is is a `BytesIO` and it's failing to write the value which you explain is `b'UNKNOWN'` and that shouldn't throw this TypeError. It'd make more sense if the value was `"b'UNKNOWN'"` That might happen if you're hitting [this line](https://github.com/python/cpython/blob/112784984784199d54176132edc38ce8c9b007c1/Lib/distutils/command/upload.py#L156) first and `value[1]` is `"b'UNKNOWN'"` which would certainly be odd.

Honestly, at this point it would seem to be a problem with one of:

- Your version of wheel
- The metadata your wheel is generating from the sdist
- Your system

**Comment by thilo-maurer** [comment]
Found the issue:

It is in this package's `setup.py`: The argument `classifiers` (line 52) requires an array, and not a tuple as value.
Replace `(` by `[` and it'll work fine.

**Comment by alex** [comment]
#91
